#!/usr/bin/env bash

FEATURE_SETS=("GWAS_beforeBH_combined" "GWAS_afterBH_combined" "GTEx")
SCENARIOS=("genetic_only" "genetic_pcs_nongenetic")
MODELS=("LinearRegression" "ElasticNet" "XGBoost")

# Make sure results_all.csv is generated by running run_all.sh and test4.py first.

echo "Generating tables for all combinations..."

for feature_set in "${FEATURE_SETS[@]}"; do
    for scenario in "${SCENARIOS[@]}"; do
        for model in "${MODELS[@]}"; do
            echo "Creating table for Feature_Set=$feature_set, Scenario=$scenario, Model=$model"
            python create_tables.py --feature_set "$feature_set" --scenario "$scenario" --model "$model" --output_prefix "table"
        done
    done
done

echo "All tables generated."
